---
title: "Data analysis"
author: "Jae Yeon Kim"
output:
  pdf_document:
    toc: yes
  html_document:
    theme: united
    toc: yes
---

# Setup 

```{r}

# Import libs

if (!require("pacman")) install.packages("pacman")
pacman::p_load(
  tidyverse, # the tidyverse framework
  tidygraph, # tidy graph manipulation
  broom, # tidying model objects
  ggpubr, # arranging ggplots
  ggthemes, # fancy ggplot themes
  MKinfer, # inferential statistics
  wBoot, # bootstrapping methods
  plotrix, # various plotting functions
  PerformanceAnalytics, # corr plots
  GGally, # corr plots
  patchwork, # easy ggarrange
  correlation, # correlation analysis
  effectsize, # effect size
  coefficientalpha, # robust coefficient alpha and omega
  psych, # psychometric analysis
  srvyr, # applying dplyr syntax to the survey package
  irr, # reliability test
  rel, # bootstrapping kappa
  strapgod, # bootstrapping
  grf, # generalized random forest framework
  kableExtra, # tables
  ggraph, # Gaussian Graphical Models
  here, # self-contained projects
  rptR # repeatability test 
)

devtools::install_github("jaeyk/makereproducible",
  dependencies = TRUE
)

library(makereproducible)

# Import custom functions
script_list <- list.files(paste0(here::here(), "/functions"),
  pattern = "*.r|*.R",
  full.names = TRUE
)

for (i in 1:length(script_list))
{
  source(script_list[[i]])
}

# for publication-friendly theme
theme_set(theme_pubr())
```

# Import data 

```{r}

# Importing data
df <- read_csv(make_here("/home/jae/validating-two-linked-fates/processed_data/processed_survey.csv"))

# Excluding other respondents (too small to calculate CIs)
df <- subset(df, race != "Other")

# Using only complete cases
df <- df[complete.cases(df), ] %>%
  as.data.frame()

# Make dummies
df <- df %>%
  mutate(
    Gender = factor(ifelse(Gender %in% c(1, 2), Gender, NA)),

    Male = factor(ifelse(Gender == 1, 1, 0)),

    Female = factor(ifelse(Gender == 2, 1, 0)),

    Democrat = factor(ifelse(party_id == 1, 1, 0)),

    Republican = factor(ifelse(party_id == 2, 1, 0)),

    for_born = ifelse(for_born %in% c(1, 2), for_born, NA),

    for_born = factor(ifelse(for_born == 2, 1, 0)),

    edu_level = scales::rescale(edu_level),

    income_level = scales::rescale(income_level)
  )

# Summary statisics - table1
df %>%
  as_survey_design(weights = WEIGHT) %>%
  group_by(race) %>%
  summarise(
    "N" = survey_count(.),
    "Age" = survey_mean(AGE),
    "Democrat" = survey_mean(as.numeric(as.character(Democrat))),
    "GOP" = survey_mean(as.numeric(as.character(Republican))),
    "Income" = survey_mean(income_level),
    "Education" = survey_mean(edu_level)
  ) %>%
  select(!contains("_se")) %>%
  mutate_at(vars(matches("Nn|Age")), function(x) round(x, 0)) %>%
  mutate_at(vars(matches("Democrat|GOP")), function(x) paste0(round(x, 2) * 100, "%")) %>%
  mutate_at(vars(matches("Income|Education")), function(x) round(x, 2)) %>%
  kable(format = "latex", booktabs = TRUE) %>%
  kable_styling(position = "center")
```

# Descriptive analysis 

## Mean and SEs

```{r}

summary_stat <- bind_rows(
  mutate(mean_group_key(df, race, linked_fate), Type = "Linked fate"),
  mutate(mean_group_key(df, race, linked_progress), Type = "Linked progress"),
  mutate(mean_group_key(df, race, linked_hurt), Type = "Linked hurt")
)

```

## Visualize

```{r}

summary_stat %>%
  ggplot(aes(
    x = fct_reorder(race, mean), y = mean,
    ymax = mean + 2 * se,
    ymin = mean - 2 * se,
    col = Type,
    shape = Type
  )) +
  geom_pointrange() +
  coord_flip() +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(
    x = "Race", y = "Mean",
    title = "Average responses by racial groups"
  ) +
  ylim(c(0, 4))

ggsave(make_here("/home/jae/validating-two-linked-fates/outputs/descriptive_stat_plot.png"))
```
## Bar plots

```{r}

# Apply to each data and bind them

p1 <- bar_plot(df %>%
  filter(race == "Asians")) +
  ggtitle("Asians")

p2 <- bar_plot(df %>%
  filter(race == "Blacks")) +
  ggtitle("Blacks")

p3 <- bar_plot(df %>%
  filter(race == "Whites")) +
  ggtitle("Whites")

p4 <- bar_plot(df %>%
  filter(race == "Latinx")) +
  ggtitle("Latinx")

p1 + p4 + p3 + p2

ggsave(here("outputs", "bar_plot.png"),
  width = 10
)
```
  
# Correlation analysis

Note that all tests are two-sided.

```{r}

table(df$race)

```

## Gaussian Model 

```{r}
g1 <- draw_ggm(df, "Asians") 
g2 <- draw_ggm(df, "Blacks")
g3 <- draw_ggm(df, "Whites")
g4 <- draw_ggm(df, "Latinx") 

g1 + g4 + g3 + g2

ggsave(here("outputs", "ggm.png"),
  width = 10, height = 12
)

```

## Pearson + Spearman

```{r}

# Fate - Progress
fate_progressp <- summarise_rci(
  df, race, "linked_fate", "linked_progress", "Pearson"
)

fate_progresss <- summarise_rci(
  df, race, "linked_fate", "linked_progress", "Spearman"
)

# Fate - Hurt
fate_hurtp <- summarise_rci(
  df, race, "linked_fate", "linked_hurt", "Pearson"
)

fate_hurts <- summarise_rci(
  df, race, "linked_fate", "linked_hurt", "Spearman"
)

# Progress - Hurt
progress_hurtp <- summarise_rci(
  df, race, "linked_progress", "linked_hurt", "Pearson"
)

progress_hurts <- summarise_rci(
  df, race, "linked_progress", "linked_hurt", "Spearman"
)

```

```{r}

# Combine the results
cor_results <- bind_rows(
  fate_progressp, 
  fate_progresss, 
  fate_hurtp, 
  fate_hurts, 
  progress_hurtp, 
  progress_hurts
) 

# Replace string patterns 
cor_results$type <- str_replace_all(cor_results$type, "linked_", "")
cor_results$type <- str_replace_all(cor_results$type, " ", "_")

# Rename values 
cor_results <- cor_results %>%
  rename("coeffs" = "r") %>%
  rename("Type" = "type")

```

## Visualize 

```{r}

cor_results %>%
  mutate(coeffs = round(coeffs, 4)) %>%
  mutate(Type = recode(Type,
    "fate_hurt" = "Fate <-> Hurt",
    "fate_progress" = "Fate <-> Progress",
    "progress_hurt" = "Progress <-> Hurt"
  )) %>%
  ggplot(aes(
    x = fct_reorder(Test, coeffs),
    y = coeffs,
    fill = Type
  )) +
  geom_bar(stat = "identity", color = "black", 
           position = position_dodge()) +
  geom_errorbar(aes(ymax = ci_upper, 
                    ymin = ci_lower), width = .2, 
                position = position_dodge(.9)) +
  facet_wrap(~race) +
  coord_flip() +
  labs(
    x = "Method", y = "Correlation coefficients",
    title = "Correlation test resuts"
  ) +
  geom_hline(aes(yintercept = c(0.7)), linetype = "dashed")

ggsave(make_here("/home/jae/validating-two-linked-fates/outputs/cor_coeffs_plot.png"))

```

# Difference-in-means analysis 

## Difference-in-means tests (T-tests)

```{r}

diff_fate_progress <- group_diff_in_means(
  df, race, linked_fate, linked_progress
)

diff_fate_hurt <- group_diff_in_means(
  df, race, linked_fate, linked_hurt
)

# Combining the results

diff_results <- bind_rows(
  mutate(diff_fate_progress,
    Outcome = "Progress - Fate"
  ),
  mutate(diff_fate_hurt,
    Outcome = "Hurt - Fate"
  )
)
```

## Visualize

```{r}

diff_results %>%
  ggplot(aes(
    x = fct_reorder(race, -diff), y = -diff,
    ymax = -diff + conf,
    ymin = -diff - conf
  )) +
  geom_pointrange() +
  labs(
    x = "Race",
    y = "Difference in means",
    title = "Difference of means test results "
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dashed"
  ) +
  facet_wrap(~Outcome)

ggsave(make_here("/home/jae/validating-two-linked-fates/outputs/diff_in_means_plot.png"))
```

# Regression analysis 

## OLS 

```{r}

df_binded <- df %>%
  # Row bind then pivot longer
  pivot_longer(
    cols = c("linked_fate", "linked_progress", "linked_hurt"),
    names_to = "DV",
    values_to = "difference"
  )

df_ols <- df_binded %>%
  group_by(DV, race) %>%
  nest() %>%
  mutate(ols = map(data, ols))

```

## Visualization

```{r}

df_tidied <- df_ols %>%
  unnest(tidied = map(ols, ~ tidy(., conf.int = TRUE)))

df_glanced <- df_ols %>%
  unnest(glanced = map(ols, broom::glance))
```

- Model fit 

```{r}

df_glanced <- df_glanced %>%
  mutate(DV = recode(DV,
    "linked_fate" = "Linked fate",
    "linked_progress" = "Linked progress",
    "linked_hurt" = "Linked hurt"
  ))

fit1 <- df_glanced %>%
  ggplot(aes(
    x = fct_reorder(DV, r.squared),
    y = r.squared
  )) +
  geom_point() +
  coord_flip() +
  labs(
    x = "",
    title = "R-squared"
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dashed"
  ) +
  facet_wrap(~race)

fit2 <- df_glanced %>%
  ggplot(aes(
    x = fct_reorder(DV, r.squared),
    y = adj.r.squared
  )) +
  geom_point() +
  coord_flip() +
  labs(
    x = "",
    title = "Adjusted R-squared"
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dashed"
  ) +
  facet_wrap(~race)

fit1 / fit2

ggsave(here("outputs", "ols_fits.png"), height = 10)
```

- Coefficients 

```{r}

df_tidied <- df_tidied %>%
  mutate(DV = recode(DV,
    "linked_fate" = "Linked fate",
    "linked_progress" = "Linked progress",
    "linked_hurt" = "Linked hurt"
  )) %>%
  filter(!grepl("cept", term)) %>%
  mutate(term = term %>%
    str_replace_all("\\(|\\)", "") %>% # remove ( )
    str_replace_all("factorrace", "") %>%
    str_replace_all("income_level", "Income") %>%
    str_replace_all("edu_level", "Education") %>%
    str_replace_all("for_born", "Foreign born") %>%
    str_replace_all("1", "") %>%
    str_replace_all("Blacks", "Black") %>%
    str_replace_all("Asians", "Asian") %>%
    str_replace_all("Whites", "White")) %>%
  mutate(DV = recode(DV,
    "fate_progress" = "Progress - Fate",
    "fate_hurt" = "Hurt - Fate"
  ))
```

```{r}

df_tidied %>%
  ggplot(aes(
    x = fct_reorder(term, estimate),
    y = estimate,
    ymax = conf.high,
    ymin = conf.low
  )) +
  geom_pointrange() +
  coord_flip() +
  labs(x = "", y = "OLS Estimate") +
  facet_grid(~DV) +
  geom_hline(
    yintercept = 0,
    linetype = "dashed"
  ) +
  facet_grid(DV ~ race)

ggsave(here("outputs", "ols_coeffs.png"))
```

## Predictions 

```{r}

df_pol <- df %>%
  pivot_longer(
    cols = c(contains("Q13")),
    names_to = "DV",
    values_to = "pol_pref"
  ) %>%
  mutate(pol_pref = as.character(pol_pref)) %>%
  mutate(pol_pref = recode(pol_pref,
      "1" = "3",
      "3" = "1"
    )) %>%
  mutate(pol_pref = as.numeric(pol_pref)) %>%
  mutate(DV = recode(DV, 
         "Q13a" = "Universal health care",
         "Q13b" = "Free college",
         "Q13c" = "Progressive taxation",
         "Q13f" = "Undocumented immigrants", 
         "Q13g" = "K-12 education",
         "Q13h" = "Criminal justice reform"))

```

```{r}
lf_results <- summarise_ols(df_pol, ols_lf, "linked_fate")

lp_results <- summarise_ols(df_pol, ols_lp, "linked_progress")

lh_results <- summarise_ols(df_pol, ols_lh, "linked_hurt")

results <- bind_rows(
          #mutate(lf_results, Type = "Linked fate"), 
          mutate(lp_results, Type = "Linked progress"),
          mutate(lh_results, Type = "Linked hurt"))

```

```{r}
results %>%
  ggplot(aes(
    x = fct_reorder(race, estimate),
    y = estimate,
    ymax = conf.high,
    ymin = conf.low,
    col = Type,
    shape = Type
  )) +
  geom_pointrange() +
  coord_flip() +
  labs(x = "", y = "OLS Estimate") +
  geom_hline(
    yintercept = 0,
    linetype = "dashed"
  ) +
  facet_wrap(~DV, ncol = 3)

ggsave(here("outputs", "predictions.png"))

```

```{r}
results %>%
  ggplot(aes(
    x = fct_reorder(race, estimate),
    y = estimate,
    ymax = conf.high,
    ymin = conf.low,
    col = Type,
    shape = Type
  )) +
  geom_point() +
  coord_flip() +
  labs(x = "", y = "OLS Estimate") +
  geom_hline(
    yintercept = 0,
    linetype = "dashed"
  ) +
  facet_wrap(~DV, ncol = 3)

ggsave(here("outputs", "predictions_no_ses.png"))
```
