---
title: "Data analysis"
author: "Jae Yeon Kim"
output:
  pdf_document:
    toc: yes
  html_document:
    theme: united
    toc: yes
---

# Setup 

```{r}

# Import libs 

if (!require("pacman")) install.packages("pacman")
pacman::p_load(
  tidyverse, # the tidyverse framework
  broom, # tidying model objects
  ggpubr, # arranging ggplots
  ggthemes, # fancy ggplot themes
  MKinfer, # inferential statistics
  wBoot, # bootstrapping methods
  plotrix, # various plotting functions
  PerformanceAnalytics, # corr plots
  GGally, # corr plots
  patchwork, # easy ggarrange
  psych, # psychometric analysis
  srvyr, # applying dplyr syntax to the survey package 
  irr, # reliability test
  rel, # bootstrapping kappa
  strapgod, # bootstrapping
  grf, # generalized random forest framework
  here, # self-contained projects
  see, # pub-ready visualization
  kableExtra # df to latex 
)

devtools::install_github("jaeyk/makereproducible",
  dependencies = TRUE
)

library(makereproducible)

# Import custom functions 
script_list <- list.files(paste0(here::here(), "/functions"),
  pattern = "*.r|*.R",
  full.names = TRUE
)

for (i in 1:length(script_list))
{
  source(script_list[[i]])
}

# for publication-friendly theme
theme_set(theme_pubr())
```

# Import data 

```{r}

# Importing data
df <- read_csv(make_here("/home/jae/validating-two-linked-fates/processed_data/processed_survey.csv"))

# Excluding other respondents (too small to calculate CIs)
df <- subset(df, race != "Other")

# Using only complete cases
df <- df[complete.cases(df), ] %>%
  as.data.frame()

# Apply weights 
df_weights <- df %>% as_survey(weights = WEIGHT) 

```

# Descriptive analysis 

## Mean and SEs

```{r}

# Not weighted
summary_stat <- bind_rows(
  mutate(mean_group_key(df, race, linked_fate), Type = "Linked fate"),
  mutate(mean_group_key(df, race, linked_progress), Type = "Linked progress"),
  mutate(mean_group_key(df, race, linked_hurt), Type = "Linked hurt")
)

# Weighted
summary_stat_weights <- bind_rows(
  mutate(mean_group_key_weight(df_weights, race, linked_fate), Type = "Linked fate"),
  mutate(mean_group_key_weight(df_weights, race, linked_progress), Type = "Linked progress"),
  mutate(mean_group_key_weight(df_weights, race, linked_hurt), Type = "Linked hurt")
)

```

```{r}
# All groups
main_summary <- df_weights %>%
  summarise(linked_fate = survey_mean(linked_fate),
            linked_progress = survey_mean(linked_progress),
            linked_hurt = survey_mean(linked_hurt))

create_table(main_summary)

# Subordiante groups
sub_summary <- df_weights %>%
  filter(race != "Whites") %>%
  summarise(linked_fate = survey_mean(linked_fate),
            linked_progress = survey_mean(linked_progress),
            linked_hurt = survey_mean(linked_hurt))

create_table(sub_summary)
```


```{r}
# Not including whites 
summary_stat_weights %>%
  filter(race != "Whites") 
  group_by(Type) %>%
  summarise(avg = mean(mean) %>% round(2))

data.frame("Types" = c("Linked fate", "Linked progress", "Linked hurt"),
           "Averages" = round(as.numeric(main_summary[1, c(1,3,5)]),2),
           "SEs" = round(as.numeric(main_summary[1, c(2,4,6)]),2)) %>%
  kable(format = "latex", booktabs = TRUE) %>%
  kable_styling(position = "center")
  
```

## Visualize results 

```{r}

# Not weighted 
nonweighted_plot <- summary_stat %>%
  ggplot(aes(
    x = fct_reorder(race, mean), y = mean,
    ymax = mean + 2*se,
    ymin = mean - 2*se, 
    col = Type, 
    shape = Type
  )) +
  geom_pointrange() +
  coord_flip() +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(
    x = "Race", y = "Mean",
    title = "Average responses by racial groups"
  ) +
  ylim(c(0,4))

# Weighted
weighted_plot <- summary_stat_weights %>%
  ggplot(aes(
    x = fct_reorder(race, mean), y = mean,
    ymax = mean + 2*mean_se,
    ymin = mean - 2*mean_se, 
    col = Type, 
    shape = Type
  )) +
  geom_pointrange() +
  coord_flip() +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(
    x = "Race", y = "Mean",
    title = "Average responses by racial groups"
  ) +
  ylim(c(0,4))

weighted_plot

ggsave(make_here("/home/jae/validating-two-linked-fates/outputs/descriptive_stat_weights.png"))
```

  
# Correlation analysis

## Bar plots

```{r}

# Not weighted 

n1 <- bar_plot(df %>%
  filter(race == "Asians")) +
  ggtitle("Asians")

n2 <- bar_plot(df %>%
  filter(race == "Blacks")) +
  ggtitle("Blacks")

n3 <- bar_plot(df %>%
  filter(race == "Whites")) +
  ggtitle("Whites")

n4 <- bar_plot(df %>%
  filter(race == "Latinx")) +
  ggtitle("Latinx")

# Weighted 

p1 <- bar_plot_weights(df %>%
  filter(race == "Asians")) +
  ggtitle("Asians (weighted)")

p2 <- bar_plot_weights(df %>%
  filter(race == "Blacks")) +
  ggtitle("Blacks (weighted)")

p3 <- bar_plot_weights(df %>%
  filter(race == "Whites")) +
  ggtitle("Whites (weighted)")

p4 <- bar_plot_weights(df %>%
  filter(race == "Latinx")) +
  ggtitle("Latinx (weighted)")

(n1 + n4) / (n3 + n2)

ggsave(here("outputs", "bar_plot_weights.png"),
  width = 10)
```
